name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: ['main']

# Vercel Remote Caching can be leveraged with Turbo to speed up builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
# env:
#   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#   TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-lint:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}apps/nextjs/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - name: Build, lint and type-check
        run: yarn turbo build lint type-check
        env:
          SKIP_ENV_VALIDATION: true
